services:

  db:

    image: postgres:latest
    container_name: postgres-furia
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: furia
    ports:
      - "5432"
    volumes:
      - furia_pgdata:/var/lib/postgresql/data

  app:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-furia
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    ports:
      - "9091:9091"
    restart: unless-stopped


volumes:
  furia_pgdata: